In [71]:
import numpy as np
import tensorly as tl

In [72]:
tensor = tl.tensor(np.arange(48).reshape((6, 4, 2)), dtype=tl.float32)

In [73]:
tensor.shape

(6, 4, 2)

In [74]:
tensor

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]],

       [[24., 25.],
        [26., 27.],
        [28., 29.],
        [30., 31.]],

       [[32., 33.],
        [34., 35.],
        [36., 37.],
        [38., 39.]],

       [[40., 41.],
        [42., 43.],
        [44., 45.],
        [46., 47.]]], dtype=float32)

In [75]:
tensor[:,:,0]

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.],
       [24., 26., 28., 30.],
       [32., 34., 36., 38.],
       [40., 42., 44., 46.]], dtype=float32)

In [76]:
tensor[:,:,1]

array([[ 1.,  3.,  5.,  7.],
       [ 9., 11., 13., 15.],
       [17., 19., 21., 23.],
       [25., 27., 29., 31.],
       [33., 35., 37., 39.],
       [41., 43., 45., 47.]], dtype=float32)

In [77]:
type(tensor)

numpy.ndarray

In [78]:
tl.unfold(tensor,mode=0)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.],
       [32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47.]], dtype=float32)

In [79]:
tl.unfold(tensor,mode=1)

array([[ 0.,  1.,  8.,  9., 16., 17., 24., 25., 32., 33., 40., 41.],
       [ 2.,  3., 10., 11., 18., 19., 26., 27., 34., 35., 42., 43.],
       [ 4.,  5., 12., 13., 20., 21., 28., 29., 36., 37., 44., 45.],
       [ 6.,  7., 14., 15., 22., 23., 30., 31., 38., 39., 46., 47.]],
      dtype=float32)

In [80]:
tl.unfold(tensor,mode=2)

array([[ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
        26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46.],
       [ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
        27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47.]],
      dtype=float32)

In [81]:
unfolding = tl.unfold(tensor, 1)
original_shape = tensor.shape
tl.fold(unfolding, mode=1, shape=original_shape)

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]],

       [[24., 25.],
        [26., 27.],
        [28., 29.],
        [30., 31.]],

       [[32., 33.],
        [34., 35.],
        [36., 37.],
        [38., 39.]],

       [[40., 41.],
        [42., 43.],
        [44., 45.],
        [46., 47.]]], dtype=float32)

In [82]:
from tensorly.decomposition import non_negative_tucker
random_state = 1234

In [96]:
core, factors = non_negative_tucker(tensor, rank=[3,2,1], n_iter_max=10, init='random', tol=0.0001, random_state=None, verbose=False, ranks=None)

In [97]:
core.shape

(3, 2, 1)

In [98]:
core

array([[[0.33428904],
        [0.9353858 ]],

       [[0.8445597 ],
        [0.580924  ]],

       [[0.30619308],
        [0.97172546]]], dtype=float32)

In [99]:
len(factors)

3

In [100]:
[f.shape for f in factors]

[(6, 3), (4, 2), (2, 1)]